### ISSUE TITLE
Develop 01

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/FinalProject#11]
## TODO
- [x] 서비스용 프론트 페이지 작성
- [x] 일반 게시판 로직 작성
- [x] DB 테이블 설계
- [x] 매핑 VO 클래스 작성
- [x] 날씨 api 이용 데이터 불러오기
- [x] 카카오 맵 api 이용 데이터 불러오기

## Feature List
- #12
- #16 
- #23 
- #24 
 -> 버그 수정 (지도 불러오기)

## 개선 사항
- 날씨 기능 지역명 띄우기 
- 지도 기능 UI 작성
- UI가 고르지 못함

**Comment by goodplan77** [comment]
2024.08.09 main 병합 완료 하였습니다.
