### ISSUE TITLE
인석

### ISSUE THREAD

**Issue by Inseak** [goodplan77/FinalProject#23]
## Description
구현할 기능에 대한 간단한 설명을 적어주세요

## TODO
- [x] **css 모듈화**
- [x] **메인네비 수정**
- [x] **날씨 데이터 가져오기**
- [ ]  **날씨 위치명 가져오기**
- [x] **이미지 생성(메인페이지 상단)**

## 기타
기타 추가 사항을 여기다 적어주세요
