### ISSUE TITLE
강경호 03

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/FinalProject#52]
## Description
1. 콘솔 로깅 작업
2. 관리자 페이지 데이터 불러오기
3. 관리자 페이지 데이터 삽입
4. 백엔드 소스코드 패키지 구조 변경

## TODO
- [x] **콘솔 로깅 작업** (설정 조정)
- [x] **관리자 페이지 데이터 불러오기**
- [x] **관리자 페이지 데이터 삽입**
- [x] **백엔드 소스코드 패키지 구조 변경**

## 기타
기타 추가 사항을 여기다 적어주세요
