### ISSUE TITLE
강경호 05

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/FinalProject#72]
## Description
1. SQL 수정 및 더미 데이터 작업
2. 파일 삭제 스케줄러? (관리자 컨트롤러와 연결)
3. 관리자 기능 - 회원 관련
4. 관리자 기능 - 회원 상세보기
5. 관리자 로그인
6. 관리자 기능 - 문의 관련
7. 관리자 기능 - 신고 관련
8. 사진 요청 컨트롤러 생성 및 역할별 분리 (회원용 , 관리자용)

## TODO
- [x] **SQL 수정 및 더미 데이터 작업**
- [x] **파일 삭제 스케줄러**
- [x] **관리자 기능 - 회원 관련 목록 불러오기**
- [x] **관리자 기능 - 회원 상세보기**
- [x] **관리자 로그인** (일부 완료)
- [x] **관리자 기능 - 문의 목록 불러오기**
- [x] **관리자 기능 - 문의 답변 달기**
- [x] **관리자 기능 - 신고 목록 불러오기** (일부 완료)
- [x] **사진 요청 컨트롤러 생성 및 역할별 분리**

## 기타
추가 작업
1. SSE 구현
