### ISSUE TITLE
인석 03

### ISSUE THREAD

**Issue by Inseak** [goodplan77/FinalProject#74]
## Description
구현할 기능에 대한 간단한 설명을 적어주세요

## TODO
- [x] **문의 모달, 햄버거바, 검색창, 알림목록, 이용약관**
- [ ] **검색창 보드 검색 및 리스트 구현** --코멘트LENGTH(오류로 인해 비활성화)
- [x] **지도 UI 수정**
- [x] **신고 ui 및 인설트**
- [x] **메모 유저정보 기입**

## 기타
기타 추가 사항을 여기다 적어주세요
