### ISSUE TITLE
강경호 06

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/FinalProject#99]
## Description
1. 좋아요 기능
2. 포인트 추가 기능
3. 관리자용 알림 기능
4. 회원용 알림 기능

## TODO
- [x] **좋아요**
- [x] **포인트 추가 기능**
- [x] **관리자용 알림 기능**
- [x] **회원용 알림**

## 기타
추가적인 관리자 기능 수정 사항 추가
1. 관리자 페이지 - 회원 상세보기
- [x] **작성 목록 불러오기 (게시글 , 댓글 , 신고)**
- [x] **회원 정보 수정**
